### ISSUE TITLE
Properly document functions in helpers.R

### ISSUE THREAD

**Issue by mcguinlu** [mcguinlu/robvis#108]
Under time-pressure and so the docs suffered! 🤦‍♂️

All the functions in the [helpers.R](https://github.com/mcguinlu/robvis/blob/master/R/helpers.R) file currently do not have any associated documentation - this makes it hard for new contributors (let alone me!) to see what's going on, and so acts a barrier to contributing.

Very happy for anyone who is looking for a good first issue to have a look at this!

**Comment by AJFOWLER** [comment]
I'll do some work on this Luke as I'm sure some of the mess is my fault!

Do you have strong feelings about how it's done? I could either [document multiple functions in one file](https://stackoverflow.com/questions/15932585/multiple-functions-in-one-rd-file), split them out into helper_*.R files individually, or just use comments!

**Comment by mcguinlu** [comment]
Hah, I actually think your bits were reasonably fine, but then I chucked mine in on top.

Absolutely fab if you had some time to run through it and add/improve the roxygen docs - it'll be a _massive_ help as we work towards [v1.0.0](https://github.com/mcguinlu/robvis/milestone/2), and having someone else try and interpret the helper functions will definitely cause some bugs to shake out (particularly the validation ones).

Based on the current approach, I'm not sure I have a right to be fussy, but I would prefer not to use the shared documentation for multiple functions (as per your linked example). I find it works well with single line functions (as in the example) because it's easy to see what the shared arguments are, but once you get up to larger functions, it requires a lot of scrolling.

Re: individual helper_*.R files vs commented single file, no real preference, as I use the "[Jump to function definition](https://support.rstudio.com/hc/en-us/articles/200710523-Navigating-Code#:~:text=To%20navigate%20a%20function%20definition,Ctrl%2BClick%20with%20the%20mouse)" rather than navigating via files.

Thanks (as always) @AJFOWLER!
