### ISSUE TITLE
Better description in opening paragraph of README

### ISSUE THREAD

**Issue by mcguinlu** [mcguinlu/robvis#117]
It would be useful to have a better description of where the `robvis`/risk-of-bias assessments generally fall within the evidence synthesis/systematic review framework at the top of the README.

This was made clear by the positive reaction to the [intro paragraph of `medrxivr` README](https://github.com/ropensci/medrxivr)

**Comment by ekothe** [comment]
Is this intention to have a short paragraph (or set of paragraphs) explaining why a person would want to create these visualisations for risk of bias? Something like... "The Cochrane Handbook says that risk of bias information should be presented graphically and provides a number of examples of how such information might be presented... This package provides a simple method for generating these figures..." (but in fancy words)

**Comment by ekothe** [comment]
Is this intention to have a short paragraph (or set of paragraphs) explaining why a person would want to create these visualisations for risk of bias? Something like... "The Cochrane Handbook says that risk of bias information should be presented graphically and provides a number of examples of how such information might be presented... This package provides a simple method for generating these figures..." (but in fancy words) 

Have you considering using some of the intro to your robvis paper? It's creative commons so it looks like you could use the verbatim text if you were so inclined.

**Comment by mcguinlu** [comment]
Yep, that's it exactly - there is a lot in the README on the "how" but not really the "what" or "why". 

I hadn't thought of using the text from the paper - that's a great idea!
