### ISSUE TITLE
Overall = FALSE for rob_traffic_light() for 'Generic' RoB tables

### ISSUE THREAD

**Issue by abannachbrown** [mcguinlu/robvis#123]
Hi Luke, 

Great tool! Really useful for rendering our RoB plots for our animal systematic reviews. Just a small feature request for the next edits. (Sorry if I'm missing any information in the Issue, I'm still getting to grips with github issues). 

Best wishes, 
Alex

**Is your feature request related to a problem? Please describe.**
Making a rob_traffic_light() plot with 'Generic' risk of bias tool (animal systematic review use-case). I do not have a "Overall" column in the data. When producing the plot with rob_traffic_light(overall = FALSE), the last column is instead written in text (rather than D3, D4, D5 etc). Further the Domain of bias that is written in text is not displayed below in "legend". 

**Describe the solution you'd like**
An option to remove the "Overall" column or hide it from the plot, while keeping the Naming of the Domains consistent. 

**Describe alternatives you've considered**
I have added a blank "Overall" column to the data and this will be rendered in the plot but will blank for that column. We can later remove the heading from the plot for publication. 

**Additional context** - Reproducible Code Example
data2 <- data.frame(
  stringsAsFactors = FALSE,
  Study = c("Study 1", "Study 2"),
  blinding = c("Low", "Some concerns"),
  random = c("Low", "Low"),
  exclusion = c("Low", "Low"),
  welfare = c("Low", "Low"),
  samplesize = c("Low", "Low")
)

rob_traffic_light(data = data2,
                  tool = "Generic", 
                  colour = "colourblind",
                   overall = FALSE
                  )

![Rplot06](https://user-images.githubusercontent.com/19909504/110645816-980dbc00-81b6-11eb-945e-13413aabdba6.png)

**Comment by mcguinlu** [comment]
Hi @abannachbrown (hope all well!) 

Thanks for flagging this - that is indeed an oversight on my part. I've added this as an issue to the upcoming big release - will post here once it is addressed.

----

NTS: when `overall=FALSE` in generic template, need to allow `robvis` to use D* for far right column.

**Comment by NadiaKeele** [comment]
Hi Luke - any idea when this oversight might be addressed, would like to use Robvis but the inclusion of a unwanted column in the diagram is an issue. thanks

**Comment by mcguinlu** [comment]
Hi @NadiaKeele - my plan is to have a "hack" weekend on `robvis` and [`triangulate`](https://github.com/mcguinlu/triangulate) on 2-4th Sept (I'm not at the stage where I need to schedule time in for side projects or else I'll never get around to it). I'll make sure to take a look at this then.

Pinging @abannachbrown for reference.

**Comment by JeffreyRStevens** [comment]
This is an awesome package. Any update on this?
