### ISSUE TITLE
R Medicine Abstract

### ISSUE THREAD

**Issue by mcguinlu** [mcguinlu/robvis#124]
Prompted by @higgi13425 on Twitter, consider submitting an abstract to the R Medicine conference once the submission window opens:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I hope you&#39;ll consider an abstract submission to <a href="https://twitter.com/r_medicine?ref_src=twsrc%5Etfw">@r_medicine</a> 2021 !</p>&mdash; Peter Higgins (@ibddoctor) <a href="https://twitter.com/ibddoctor/status/1373946633491251201?ref_src=twsrc%5Etfw">March 22, 2021</a></blockquote> 

@AJFOWLER @rdboyes, I'd be keen to include you as authors on this given the work you've done on the package recently, unless you have any objections?

**Comment by rdboyes** [comment]
No objections at all - much appreciated!

**Comment by AJFOWLER** [comment]
Thanks Luke, that'd be great.

Let me know if you need help putting it together.
