### ISSUE TITLE
problem with preparing sheet

### ISSUE THREAD

**Issue by drvatanpour** [mcguinlu/robvis#150]
**Describe the bug**
in the ROBINS-I all judgments are as high, low, no information .. but uploading a sheet with this format is not acceptable for the system, and other words like serious, critical, and.. are suggested. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mcguinlu** [comment]
Hi @drvatanpour,

The acceptable values for the ROBINS-I tool are: 

- Critical
- Serious
- Moderate
- Low
- No information 

These are taken straight from the tool itself - more information can be found via the [riskofbias.info](https://www.riskofbias.info/) page for [ROBINS-I](https://www.riskofbias.info/welcome/home/current-version-of-robins-i/robins-i-tool-2016).
