### ISSUE TITLE
y_title argument not changing axis label in "Generic" template

### ISSUE THREAD

**Issue by mcguinlu** [mcguinlu/robvis#97]
As noticed when creating the image for Issue #96, the `y_title` argument for the "Generic" template does not seem to actually change the title of this axis from "Study" (to "Test2" in the example below). 

``` r
rob_traffic_light(
  data_rob2,
  "Generic",
  psize = 10,
  x_title = "Test",
  y_title = "Test2",
  judgement_title = "Test3",
  judgement_labels = c("1", "2", "3", "4", "5", "6")
)
```
![Rplot](https://user-images.githubusercontent.com/41202585/95059025-3d949f00-06f0-11eb-8d63-97abf794ace6.png)

This is because, at present, the title of this axis is still hardcoded ([see this line](https://github.com/mcguinlu/robvis/blob/7f804581cf90a7bf2544fb4ab5c5b5fc68f88523/R/rob_traffic_light.R#L970)) - this needs to be changed so that the value passed to the y_title argument is used.

**Comment by AJFOWLER** [comment]
Hi Luke, I looked at fixing this with my last PR but reckon that we could actually put a huge amount of the traffic light plot generation into a single function that is then called by each tool as required, and implement this? Happy to look into doing this, but not sure if overlaps with any ongoing plans you have!

**Comment by mcguinlu** [comment]
This specific problem has been solved, but a larger refactoring of the plotting code is on the cards.
